/** Operator-run real-source replay. Inputs are retained native observations and
 * actual repository/spec files, not fixtures generated by this check.
 * Run in the documented credential-free test container, never a live grant.
 */
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { analyzeWorkspace, discoveryPolicies, nativeDiscovery, prepareWorkspaceImport } from "../extensions/datahub-agent/integration/native-discovery.mjs";

const directory = process.argv[2];
if (!directory) throw new Error("Supply the captured input directory");
const load = async name => JSON.parse(await readFile(join(directory, name), "utf8"));
const policy = await load("policy.json");
const observed = await load("catalog.json");
const baseline = await load("baseline-report.json");
const cases = {};
for (const [name, path, entrypoint, labels] of [
  ["etl", "src/sales_datamart/etl.py", "run_etl", { source: "scope-0", target: "scope-1" }],
  ["summary", "src/sales_datamart/summary.py", "main", { engine: "scope-1" }],
]) {
  const request = { selection: ".", pythonPath: path, entrypoint, pluginId: "legacy-static" };
  const description = await analyzeWorkspace(policy, request);
  const connections = Object.fromEntries(description.connections.map(item => [item.connection_id, labels[item.label]]));
  assert.ok(Object.values(connections).every(Boolean));
  const urns = new Set(Object.values(connections).flatMap(id => policy.catalogScopes[id].allowed_dataset_urns));
  const catalog = Object.fromEntries([...urns].map(urn => [urn, observed.catalog[urn]]));
  const selected = { ...request, connections, snapshotSha256: description.snapshotSha256 };
  const response = await analyzeWorkspace(policy, selected, catalog, observed.relatedCatalog);
  assert.deepEqual(response, baseline[name].analysis.response, `${name}: full preview must match the pre-integration real-source result, not just field counts`);
  const { pluginId, ...defaultRequest } = selected;
  assert.deepEqual(await analyzeWorkspace(policy, defaultRequest, catalog, observed.relatedCatalog), response);
  cases[name] = response;
}

// Synthetic trusted context ONLY to exercise the real Host adapter without
// acquiring a user's credentials. This is not a login/grant or live ACL test.
const actor = { key: "a".repeat(48), tenant: "isolated-functional-replay", urn: "urn:li:corpuser:isolated-functional-replay" };
let activeChecks = 0;
const apiPolicy = await load("api-policy.json");
const context = { actor, sources: discoveryPolicies({ [actor.key]: [apiPolicy] }).get(actor.key), assertActive() { activeChecks++; } };
const request = { requestId: randomUUID(), action: "analyze_workspace", sourceId: apiPolicy.sourceId, selection: ".", pluginId: "openapi-operations", pluginConfig: { serviceId: "datahub-analytics" } };
const listing = await nativeDiscovery(JSON.stringify({ requestId: randomUUID(), action: "list_plugins" }), context);
assert.deepEqual(new Set(listing.plugins.map(item => item.manifest.id)), new Set(["legacy-static", "openapi-operations"]));
const api = await nativeDiscovery(JSON.stringify(request), context);
assert.equal(api.requestId, request.requestId);
assert.equal(api.format, "dataflow-discovery.plugin-preview/1");
const nodes = api.result.graph.nodes;
assert.deepEqual(nodes.filter(node => node.kind === "asset").map(node => node.name), ["POST /datahub_usage_events/_search"]);
// Contract node arrays are ordered by stable ID, not request/response role.
assert.deepEqual(nodes.filter(node => node.kind === "port").map(node => [node.name, node.direction, node.fields]).sort((a, b) => a[0].localeCompare(b[0])), [
  ["request:application/json", "input", [{ path: "/", nativeType: "string" }]],
  ["response:200:application/json", "output", [{ path: "/", nativeType: "string" }]],
]);
assert.deepEqual(api.result.graph.edges, []);
assert.equal(api.publicationAuthorized, false);
assert.equal(api.result.runtimeVerified, false);
await assert.rejects(nativeDiscovery(JSON.stringify({ ...request, pluginId: "not-registered" }), context), /plugin_not_registered/);
await assert.rejects(nativeDiscovery(JSON.stringify({ ...request, pluginConfig: {} }), context), /plugin_schema_invalid/);
await assert.rejects(nativeDiscovery(JSON.stringify({ ...request, selection: "../outside" }), context), /invalid_workspace_selection/);
await assert.rejects(prepareWorkspaceImport(request, { discoverySources: context.sources }), /plugin_preview_only/);
assert.ok(activeChecks >= 4);
console.log(JSON.stringify({ status: "PASS", scope: "isolated_real_source_host_bridge_replay", catalogFresh: false, identityVerified: false,
  modelVerified: false, listing, api, cases, checks: ["full_etl_preview_equivalence", "full_summary_preview_equivalence", "explicit_and_default_legacy_equivalence",
    "actual_registered_plugins", "actual_host_to_python_plugin_preview", "official_api_declarations", "unknown_plugin_no_fallback", "required_config", "source_selection", "preview_not_import"] }));
